name: job-dependencies
on: 
  push:
    branches: ['master']
  pull_request: 
    branches: ['master']
  workflow_dispatch: 
jobs:
  job1:
   env: 
    JOB1_VARIABLE: "This is the JOB1 variable"
   strategy: 
     matrix:
       version: [10,12,14]
       os: [ubuntu.latest, windows.latest, macOS.latest]
   runs-on: ${{matrix.os}}
   steps: 
    - run: echo $JOB1_VARIABLE
  job2:
    env:
     JOB2_VARIABLE: "This is the variable for job 2"
    strategy: 
     matrix:
       version: [10,12,14]
       os: [ubuntu.latest, windows.latest, macOS.latest]
    runs-on: ${{matrix.os}}
    steps: 
    - run: ./server.sh
  job3:
      needs: job2
      strategy: 
        matrix:
         version: [10,12,14]
         os: [ubuntu.latest, windows.latest, macOS.latest]
      runs-on: ${{matrix.os}}
      steps: 
       - run: echo "Runs if Job 2 is successful"
  job4:
      if: always()
      needs: job2
      strategy: 
       matrix:
         version: [10,12,14]
         os: [ubuntu.latest, windows.latest, macOS.latest]
      runs-on: ${{matrix.os}}
      steps: 
      - run: echo "Job 4 runs irrespective of the outcome of Job 2"
    
    
    
